apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  containers:
    - name: jenkins
      image: singen/jenkub
      ports:
        - name: ui
          containerPort: 8080
          # hostPort: 8080
        - name: discovery
          containerPort: 50000
          # hostPort:50000
  #     volumeMount:
  #       - name: "jenkins-data"
  #         mountPath: "/var/jenkins_home"
  #  volumes:
  #   - name: "jenkins-data"
  #     hostPath:
  #       path: "/home/docker/jenkins"
