apiVersion: v1
kind: Service
metadata:
  labels:
    name: jenkins
  name: jenkins
spec:
  type: NodePort
  ports:
  - name: ui
    port: 8080
    targetPort: ui
    protocol: TCP
  - name: discovery
    port: 50000
    targetPort: discovery
    protocol: TCP
  selector:
    name: jenkins
    # role: leader
