---
kind: ReplicationController
apiVersion: v1
metadata:
  name: jenkub-leader
  labels:
    name: jenkub
    role: leader
spec:
  replicas: 1
  selector:
    name: jenkub
    role: leader
  template:
    metadata:
      name: jenkub-leader
      labels:
        name: jenkub
        role: leader
    spec:
      containers:
      - name: jenkub-http
        image: singen/jenkub
        ports:
        - name: jenkub-http
          containerPort: 8080
        - name: jenkub-disco
          containerPort: 50000
